CleaningCleaningBundle_homepage:
    pattern:  /
    defaults: { _controller: CleaningBundle:Page:index }
    requirements:
        _method:  GET




CleaningBundle:
    resource: "@CleaningBundle/Controller/"
    type: annotation
    prefix: /

