parameters:
#    cleaning.example.class: Cleaning\CleaningBundle\Example

services:
#    cleaning.example:
#        class: %cleaning.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
